{
    'name': 'HDC Admin',
    'version': '18.0.1.1.0',
    'summary': 'ХДК ERP системийн админ удирдлага, дүр ба нэвтрэлтийн лог',
    'category': 'Administration',
    'author': 'HDC',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'web',
        'hr',
        'hdc_hr',
        'hdc_attendance',
        'hdc_erp_base',
    ],
    'data': [
        'security/system_roles.xml',
        'security/ir.model.access.csv',
        'views/res_users_views.xml',
        'views/admin_views.xml',
        'views/admin_menu.xml',
    ],
    'installable': True,
    'application': False,
}
